INSERT INTO DRUG_DETAILS VALUES ('PR1', 'PARACETAMOL', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-10-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('CR2', 'CROCIN', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-12-2020', 'dd-MM-yyyy'), 'Serum');
INSERT INTO DRUG_DETAILS VALUES ('PD3', 'PENADOL', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-09-2020', 'dd-MM-yyyy'), 'Alkem health Science');
INSERT INTO DRUG_DETAILS VALUES ('PD1', 'PAN D', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('ED1', 'ESC D', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('AS1', 'ASPIRIN', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('DO1', 'DOLO', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('EA1', 'ECOSPRIN AV', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('CE1', 'CELIN 500', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('SU1', 'SUPRADYN', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('BE1', 'BECADEXMIN', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('EV1', 'EVION 400', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('LI1', 'LIMCEE 500', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('TE1', 'TELMA 500', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('BE2', 'BECASULE', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('CO1', 'CORONIL', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('NO1', 'NORFLOX TZ', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('MO1', 'MORPHINE', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('OM1', 'OMNI', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');
INSERT INTO DRUG_DETAILS VALUES ('AM1', 'AMLOGARD', parsedatetime('12-10-2023', 'dd-MM-yyyy'), parsedatetime('21-08-2020', 'dd-MM-yyyy'), 'Cipla');



INSERT INTO DRUG_LOCATION_DETAILS VALUES('1', 'Chennai', 100, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('2', 'Bangalore', 100, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('3', 'Pune', 100, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('4', 'Hyderabad', 100, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('5', 'Chennai', 100, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('6', 'Bangalore', 100, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('7', 'Pune', 100, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('8', 'Hyderabad', 100, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('9', 'Chennai', 100, 'PD3');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('10', 'Bangalore', 100, 'PD3');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('11', 'Pune', 100, 'PD1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('12', 'Bangalore', 100, 'PD1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('13', 'Pune', 100, 'ED1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('14', 'Bangalore', 100, 'ED1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('15', 'Pune', 100, 'AS1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('16', 'Bangalore', 100, 'AS1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('17', 'Pune', 100, 'EA1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('18', 'Bangalore', 100, 'EA1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('19', 'Pune', 100, 'CE1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('20', 'Bangalore', 100, 'CE1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('21', 'Pune', 100, 'SU1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('22', 'Bangalore', 100, 'SU1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('23', 'Pune', 100, 'BE1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('24', 'Bangalore', 100, 'BE1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('25', 'Pune', 100, 'EV1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('26', 'Bangalore', 100, 'EV1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('27', 'Pune', 100, 'LI1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('28', 'Bangalore', 100, 'LI1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('29', 'Pune', 100, 'TE1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('30', 'Bangalore', 100, 'TE1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('31', 'Pune', 100, 'BE2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('32', 'Bangalore', 100, 'BE2');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('33', 'Pune', 100, 'CO1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('34', 'Bangalore', 100, 'CO1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('35', 'Pune', 100, 'NO1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('36', 'Bangalore', 100, 'NO1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('37', 'Pune', 100, 'MO1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('38', 'Bangalore', 100, 'MO1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('39', 'Pune', 100, 'OM1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('40', 'Bangalore', 100, 'OM1');

INSERT INTO DRUG_LOCATION_DETAILS VALUES('41', 'Pune', 100, 'AM1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('42', 'Bangalore', 100, 'AM1');


INSERT INTO DRUG_LOCATION_DETAILS VALUES('43', 'Pune', 100, 'DO1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('44', 'Bangalore', 100, 'DO1');